celestekrishna/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^preludered/', include('preludered.urls')),
    url(r'^admin/', admin.site.urls),
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^works$', views.works, name='works'),
    url(r'^live$', views.live, name='live'),
    url(r'^connect$', views.connect, name='connect')
]

preludered/urls.py
from django.conf.urls import url
from . import views

app_name = 'preludered'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^nav/prelude-red$', views.nav_prelude_red, name='nav_prelude_red'),
    url(r'^nav/libretto/(?P<track>[0-9]+)$', views.nav_libretto, name='nav_libretto'),
    url(r'^nav/notes$', views.nav_notes, name='nav_notes'),
    url(r'^nav/credits$', views.nav_credits, name='nav_credits'),
    url(r'^nav/music-videos$', views.nav_music_videos, name='nav_music_videos')
]

home/models.py
from django.db import models

# Create your models here.

preludered/models.py
from django.db import models

# Create your models here.


class Music(models.Model):
    track_number = models.IntegerField(default=0)
    title = models.CharField(max_length=255, default='')
    image = models.FileField(upload_to='public/uploads/', default='')

    def libretto_image(self):
        return '<img src="/static/%s" height="100" />' % self.image

    libretto_image.allow_tags = True

    class Meta:
        verbose_name = 'Music'
        verbose_name_plural = 'Music'


class Notes(models.Model):
    image = models.FileField(upload_to='public/uploads/', default='')
    title = models.CharField(max_length=255, default='')
    order = models.IntegerField(default=0)

    def admin_image(self):
        return '<img src="/static/%s" height="100" />' % self.image

    admin_image.allow_tags = True

    class Meta:
        verbose_name = 'Note'
        verbose_name_plural = 'Notes'


class Credits(models.Model):
    order = models.IntegerField(default=0)
    image = models.FileField(upload_to='uploads/', default='')
    title = models.CharField(max_length=255, default='')

    def admin_image(self):
        return '<img src="/static/%s" height="100" />' % self.image

    admin_image.allow_tags = True

    class Meta:
        verbose_name = 'Credits'
        verbose_name_plural = 'Credits'


class MusicVideos(models.Model):
    order = models.IntegerField(default=0)
    title = models.CharField(max_length=255, default='')
    href = models.CharField(max_length=500, default='')

    class Meta:
        verbose_name = 'Music Video'
        verbose_name_plural = 'Music Videos'

home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home/home.html')

def works(request):
    return render(request, 'home/works.html')

def live(request):
    return render(request, 'home/live.html')

def connect(request):
    return render(request, 'home/connect.html')

preludered/views.py
from django.shortcuts import render, get_object_or_404

from .models import Music, Notes, Credits, MusicVideos

import random


def index(request):
    auto_play = request.session.get('auto_play', 1)
    request.session['auto_play'] = 0

    return render(request, 'preludered/index.html',
                  {'body_class': 'preludered', 'auto_play': auto_play})


def nav_prelude_red(request):
    return render(request, 'preludered/nav-prelude-red.html')


def nav_libretto(request, track):
    music = Music.objects.order_by('track_number')
    data = {
        'music': music,
        'start_track': track
    }
    return render(request, 'preludered/nav-libretto.html', data)


def nav_notes(request):
    notes = Notes.objects.order_by('order')
    data = {
       'notes': notes,
       'start_pos': random.randrange(notes.count() + 1)
    }
    return render(request, 'preludered/nav-notes.html', data)


def nav_credits(request):
    credits = Credits.objects.order_by('order')
    return render(request, 'preludered/nav-credits.html', {'credits': credits})


def nav_music_videos(request):
    music_videos = MusicVideos.objects.order_by('order')
    return render(request, 'preludered/nav-music-videos.html', {'music_videos': music_videos})

home/templates/home/home.html
{% extends "templates/common/main.html" %}
{% load static %}

{% block content %}
<div class="page">


</div>
{% endblock content %}

home/templates/home/live.html
{% extends "templates/common/main.html" %}
{% load static %}


{% block content %}
<div class="page">
    <h2>Upcoming Performances</h2>
    <p class="bandsInTown">
       <script charset="utf-8" src="https://widget.bandsintown.com/main.min.js"></script>
        <a class="bit-widget-initializer" data-artist-name="CelesteKrishna" data-display-local-dates="false" data-display-past-dates="true" data-auto-style="false" data-text-color="#000000" data-link-color="#000000" data-popup-background-color="rgba(0,0,0,0)" data-background-color="rgba(0,0,0,0)" data-display-limit="15" data-link-text-color="#FFFFFF"></a>
    </p>

    <h2><a href="javascript: $('.vids').slideToggle();">Live Videos</a></h2>
    <div class="vids">
        <p>
            <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/ew8W0ryI9ac?rel=0" frameborder="0" allowfullscreen></iframe>
        </p>

        <p>
           <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/EVkN_gAS_1o?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
        </p>
    </div>


</div>
{% endblock content %}

home/templates/home/works.html
{% extends "templates/common/main.html" %}
{% load static %}


{% block content %}
<div class="page">
    <h2>Celeste Krishna</h2>
    <p><a href="{% url 'preludered:index' %}">Prelude Red (2017)</a></p>

    <h2>Mixtape</h2>
    <p><a href="https://celestekrishna.bandcamp.com/album/ft-celeste-mixtape" target="_blank">Ft. Celeste (2012)</a></p>

    <h2>Monarchs</h2>
    <p><a href="https://open.spotify.com/album/5kZrnnhRmJqorUzwiNoae8" target="_blank">The Rise and Fall (2011)</a></p>
    <p><a href="https://open.spotify.com/album/3om2dkdDc6JLhiDlDvYw8Z" target="_blank">Those Words, Those Frames (2009)</a></p>
    <p><a href="https://open.spotify.com/album/2O1iEwgh6BmYVzNAyrgOBN" target="_blank">The Oak EP (2008)</a></p>
</div>
{% endblock content %}

preludered/templates/preludered/index.html
{% extends "templates/common/main.html" %}
{% load static %}

{% block other_head %}
<link rel="stylesheet" href="{% static 'preludered/pr-main.css' %}">
<link  href="//cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css" rel="stylesheet">
{% endblock %}


{% block content %}

<div class="pagePreludered">

    <div class="columnRight">

        <div class="playerDirections">
            <img src="{% static 'img/player-directions-whenpaused.png' %}">
        </div>
        <div class="playerWrap">
            <a href="javascript: player.pause();" class="playerCenterCircle"></a>
            <img class="playerClip" src="{% static 'img/player-clip.png' %}">
            <img id="playerCircle" src="{% static 'img/player-circle.png' %}" usemap="#Map">
            <map name="Map" id="Map">
                <area alt="" title="" href="javascript: player.play(1);" shape="poly" coords="172,173,98,31,173,11" />
                <area alt="" title="" href="javascript: player.play(2);" shape="poly" coords="175,173,176,12,251,32" />
                <area alt="" title="" href="javascript: player.play(3);" shape="poly" coords="173,170,253,34,311,87" />
                <area alt="" title="" href="javascript: player.play(4);" shape="poly" coords="175,170,312,91,334,155" />
                <area alt="" title="" href="javascript: player.play(5);" shape="poly" coords="177,174,333,157,322,234" />
                <area alt="" title="" href="javascript: player.play(6);" shape="poly" coords="175,175,320,234,276,297" />
                <area alt="" title="" href="javascript: player.play(7);" shape="poly" coords="175,177,276,299,208,332" />
                <area alt="" title="" href="javascript: player.play(8);" shape="poly" coords="171,175,206,332,132,331" />
                <area alt="" title="" href="javascript: player.play(9);" shape="poly" coords="173,175,130,330,64,294" />
                <area alt="" title="" href="javascript: player.play(10);" shape="poly" coords="169,175,63,292,21,231" />
                <area alt="" title="" href="javascript: player.play(11);" shape="poly" coords="168,173,21,228,12,154" />
                <area alt="" title="" href="javascript: player.play(12);" shape="poly" coords="168,171,13,152,41,81" />
                <area alt="" title="" href="javascript: player.play(13);" shape="poly" coords="166,168,40,79,95,33" />
            </map>

        </div>

    </div>

    <div class="columnLeft">
        <div class="columnLeftPage">

            {% include "preludered/nav-prelude-red.html" %}

        </div>

        <div class="nav">
            <img src="{% static 'img/nav.png' %}" usemap="#image-map">
            <map name="image-map">
                <area href="#" class="nav-prelude-red" coords="65,1,161,12" shape="rect">
                <area href="#" class="nav-libretto" coords="49,14,109,29" shape="rect">
                <area href="#" class="nav-notes" coords="126,18,173,28" shape="rect">
                <area href="#" class="nav-credits" coords="24,34,78,46" shape="rect">
                <area href="#" class="nav-music-videos" coords="96,33,199,45" shape="rect">
                <area href="https://bit.ly/preludereddigital " target="_blank" class="nav-digital-copy" coords="2,49,95,63" shape="rect">
                <area href="https://bit.ly/preluderedalbum" target="_blank" class="nav-signed-album" coords="115,50,220,63" shape="rect">
            </map>
        </div>

    </div>


</div>

{% endblock content %}


{% block other_foot %}
<script src="//cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.js"></script>
<script src="{% static 'preludered/howler.js' %}"></script>
<script src="{% static 'preludered/pr-player.js' %}"></script>

<script type='text/javascript'>
$(document).ready(function(){
    player.init();
    nav.init();

    track = Math.floor((Math.random() * player.totalTracks) + 1);

    {% if auto_play == 1 %}
        player.play(track);
    {% else %}
        player.positionCircle(track);
    {% endif %}
});
</script>

{% endblock %}

preludered/templates/preludered/nav-credits.html
{% load static %}
<div class="credits">
    <div class="fotorama"
         data-maxheight="406"
         data-allowfullscreen="true"
         data-nav="false">
        {% for credit in credits %}
        <img src="{% static credit.image %}">
        {% endfor %}
    </div>
</div>

<script type="text/javascript">
    $('.fotorama').fotorama();
</script>

preludered/templates/preludered/nav-libretto.html
{% load static %}
<div class="libretto">
    <div class="fotorama"
         data-width="400"
         data-allowfullscreen="true"
         data-nav="false"
         data-loop="true"
         data-startindex="{{ start_track }}">
        {% for track in music %}
        <img src="{% static track.image %}">
        {% endfor %}
    </div>
</div>
<script type="text/javascript">
$('.fotorama').fotorama();
</script>

preludered/templates/preludered/nav-music-videos.html
<div class="musicVideos">
    <div class="fotorama"
             data-allowfullscreen="true"
             data-nav="false"
             data-shuffle="true"
             data-width="560">
             {% for video in music_videos %}
                <a href="{{ video.href }}" data-caption="{{ video.title }}"></a>
             {% endfor %}
    </div>
</div>

<script type="text/javascript">
    $('.fotorama').fotorama().on('fotorama:loadvideo', function() {
        if(player.playlist[player.currentTrack].playing())
        {
            player.pause();
        }
    });
</script>
<style type="text/css">
    div.fotorama__caption {
        top: 12px;
        width: 100%;
        text-align: center;
        height:50px;
    }
    div.fotorama__caption__wrap {
        background:none;
        color:#ffffff;
        font-family: 'Libre Baskerville', serif;
    }
</style>

preludered/templates/preludered/nav-notes.html
{% load static %}

<div class="notes">
    <div class="fotorama"
         data-maxheight="406"
         data-allowfullscreen="true"
         data-nav="false"
         data-startindex="{{ start_pos }}">
        {% for note in notes %}
        <img src="{% static note.image %}">
        {% endfor %}
    </div>
</div>

<script type="text/javascript">
    $('.fotorama').fotorama();
</script>

preludered/templates/preludered/nav-prelude-red.html
{% load static %}
<div class="albumCover">
    <img class="cover" src="{% static 'img/pr-album-cover.jpg' %}">
</div>

preludered/templates/preludered/pr-main.html
{% load static %}
<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Celeste Krishna</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="manifest" href="site.webmanifest">
        <link rel="apple-touch-icon" href="{% static 'icon.png' %}">
        <!-- Place favicon.ico in the root directory -->

        <link href="//fonts.googleapis.com/css?family=Libre+Baskerville:400,400i," rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
        <link rel="stylesheet" href="{% static 'preludered/pr-main.css' %}">
    </head>
    <body>


        {% block content %}{% endblock %}


        <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
        <script src="//code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-3.2.1.min.js"><\/script>')</script>
        <script src="{% static 'js/plugins.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
        <script src="{% static 'preludered/pr-player.js' %}"></script>

        <link  href="//cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css" rel="stylesheet">
        <script src="//cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.js"></script>

        <!-- Google Analytics: change UA-XXXXX-Y to be your site's ID. -->
        <!--
        <script>
            window.ga=function(){ga.q.push(arguments)};ga.q=[];ga.l=+new Date;
            ga('create','UA-XXXXX-Y','auto');ga('send','pageview')
        </script>
        <script src="https://www.google-analytics.com/analytics.js" async defer></script>
        -->
    </body>
</html>